services:

  app:
    build:
      dockerfile: ./docker/app/Dockerfile
    restart: always

  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    ports:
      - "9000:80"

  mysql:
    build:
      dockerfile: ./docker/mysql/Dockerfile
    restart: always
    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_ROOT_PASSWORD=root
